hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "7ffe1954587c77dfba1cf8eb9b2ea743671fa6e63f9e7a2f258119d42e14eefe"

[[files]]
file = "README.md"
hash = "44c990be7f8cac622a28ac1b9f35ceae2e4a879b88c022be1e27b1933842de94"

[[files]]
file = "config/paxi/datapacks/cobblemon-additions.pw.toml"
hash = "eb5c5c1a58190310d6076bcdca77917e524799a1a2463435de9aaece2254210d"
metafile = true

[[files]]
file = "config/paxi/datapacks/cobblemon-alphas.pw.toml"
hash = "32967bd90daf3871d858813068f07e3446ac8c361097fa515c62c08e4749e426"
metafile = true

[[files]]
file = "config/paxi/datapacks/cobbletowns.pw.toml"
hash = "00a307724f8b64e0b9987803538392b7b3c6fb524d76f3beaefc7f5b294deaa7"
metafile = true

[[files]]
file = "config/paxi/datapacks/vivillon-pride-patterns.pw.toml"
hash = "a1484d0e4c283ce0aabf0d0efabda9e8791c6ebb12286952b78ecf9671aa2b09"
metafile = true

[[files]]
file = "configureddefaults/config/betterf3.json"
hash = "c967de25c9263dfbd2a1086bc707446587d6071d221ba19d342206b852c97976"

[[files]]
file = "configureddefaults/config/emi.css"
hash = "cf7f63906cfad319910e889c70898708fb26522f93aac979f2e838659c0f579a"

[[files]]
file = "configureddefaults/config/fightorflight.json5"
hash = "7faf0688a9fbda8a15bd8433950db42b6f96e3d267eecae4cc9d742c02f37608"

[[files]]
file = "configureddefaults/config/fightorflight_moves.json5"
hash = "b5588fe103f8bd8ffaad0c0d0d327a902328a6e2175f4be762e30e480c080ce7"

[[files]]
file = "configureddefaults/config/figura.json"
hash = "45d1b9d9bf59fbd6a384fe8a7d1db75f7364276e17819f738c670202be5d4fd4"

[[files]]
file = "configureddefaults/config/moreculling.toml"
hash = "a8bf3422a425d5f2e98a3efe1f31b78c703c2630c498fe4012496723f968c443"

[[files]]
file = "configureddefaults/config/waystones-common.toml"
hash = "ac3b5c7ea9df57bfee44351e66745b37bb1b7ca947dffa72760f6dc76ebc52aa"

[[files]]
file = "configureddefaults/config/xaerominimap.txt"
hash = "9f4afef6c3307c3b418d9b897b912c7cbd33eacbceafd3a78c5f1abafc77f4b8"

[[files]]
file = "configureddefaults/options.txt"
hash = "8a36175826289b60d9e454ff730eeed15ce23f7e59dd684bd59301ff128a9400"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "8a9a92db01486e4f8d3a7370a6cbf6e59a12d1ef15c24b375ebce75500e78afc"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "d68190d63a0cef38d5d95aac2fe0ee5d31a7b43f195da073589c5291583171ff"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "eb5e497816518af0301e6c47cfa8009ee378c109909422a8aec70717c8e3f928"
metafile = true

[[files]]
file = "mods/azurelib.pw.toml"
hash = "70519c5807810bedb4916bb37b6f869db2309b3405b3fabc71190d6a2ae3515d"
metafile = true

[[files]]
file = "mods/bad-horse-fix.pw.toml"
hash = "500add089fdd5cc8a2a7840378c55d54cca76ac0fcfe12429d602347e23d060d"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "268f35112d9b1637f9d5e7beea999d9dbda8ae746d1d98fb2cd8e23c5f5ac98f"
metafile = true

[[files]]
file = "mods/better-ping-display.pw.toml"
hash = "cc2e6dda94a7a6f5487843cafe569d8044bf9482cbf03f062cf4595f1fb05281"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "e1f1588b18947699ddc9b4f7c5b5406c5559155b8cb52dcd0f203c07c31cd0b8"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "c9aca350959a8936b054c7164fb55d789ab1e0d38cff2af48b78f70af2bc0c6d"
metafile = true

[[files]]
file = "mods/bl4cks-sit.pw.toml"
hash = "70c9b1717eeb973a2c60ef839bf29f5c04b6b666ba47bb8d94c648103ad05a4d"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "00a6a59105f7bc307cf04c1dfb129b300c29a4cb550a5825cacdb54dbc598c68"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "08efd066ced1a64fdf4b0737a8a14c40ed7676d23fda5b8e614b6fc5caade5cf"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "1e35659b538887b310477e8581c8fbcec93b407c1b9ba04a7c8c05d060a33eb7"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/cobblemon-capture-xp.pw.toml"
hash = "bb38e28ee3609ff6080c048395a125fdfd0b820efd69d26f1a9026a3a0441a71"
metafile = true

[[files]]
file = "mods/cobblemon-fight-or-flight-reborn.pw.toml"
hash = "23ff347565f4c5fc434d4be43ee2799310e7f7cc7c6d0334fec71456f37ed812"
metafile = true

[[files]]
file = "mods/cobblemon-integrations.pw.toml"
hash = "69c59f5d7eaf9489c5e0f870e2b5bf1d5c5e9cd8dbff028f85dad5896b4cd09f"
metafile = true

[[files]]
file = "mods/cobblemon-move-inspector.pw.toml"
hash = "324bb537b3e60bd23820648cdbfe9ec80c0650a5aee571fe5311aa358f1d2428"
metafile = true

[[files]]
file = "mods/cobblemon-size-variations.pw.toml"
hash = "b0a316d9257fee634fde527f3fae16df4a1c1314088b15fa1ca884ee46f807d4"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "e3cb1eb238192071af93f764e3ff2c493f4f437802bb56273f664bafdea13f1d"
metafile = true

[[files]]
file = "mods/cobblepedia.pw.toml"
hash = "777d43c32847ac522bcad868f85c430eb0cea08d4a6af7d224b1458d11667d3d"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "874f578662fd07d02038e7d31e475ed9e1bbda2be31d5067cba21440289e68d8"
metafile = true

[[files]]
file = "mods/configured-defaults.pw.toml"
hash = "edccf044df3d6519c3f8cb35e1044687d1b5bdc676fdce919d0844a4d2515685"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "7decaf223cb308d65bf44a7118a2ceb5d26a1bc1be5085c2132fa3035a718cca"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "5980bd5b63b19c2393a55721f74a6ae2f35a2c42252becacb29af8eea1173c64"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "e7ab61139edaca7ebf16131d8292a257e45b3dc1b027234ce2b4f0f27f850004"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "7f657c9071754b89ccfa3b138c33e73fb8414384b6c442396a951a6ad97e4956"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "699cacace84b427ebcd0766af90c39e8396e9fecd03821558658041cb93e09aa"
metafile = true

[[files]]
file = "mods/creeper-overhaul.pw.toml"
hash = "cd4c4ec6ef26d2b61e0cb0bdd398e8d528b88ebf739fc0898bc8cb2f7a88debb"
metafile = true

[[files]]
file = "mods/ct-overhaul-village.pw.toml"
hash = "5969466d47d5673feef1bdcd1dcd6539fdf11c0d99c019c132c8ae4108e0a2c0"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "b2abfcd26485e785f6836f6b0d3844a5ba00a97f8c0689aa44c44d3a072ca43a"
metafile = true

[[files]]
file = "mods/displaycase.pw.toml"
hash = "549bd2251ec132b207abdadbd26e0ac3b48ee275d04193cfd26a6869bf0d33ef"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "e25f8d5bbea8e14e71fc686644c34f588b97e8e655286101e92824fb547c798d"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "4e6cce2a40f56a58a5dffa924b05a27b7cc618c4c9afd611e5a2ff247a5a1065"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "b42ea604c46fc73d9474ebc9d6d3d64a1efe6b9d5df8512c71a86f820eb8a105"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "f98bb58144f3b207bc5ebc99d898e1c2557924e27f403e670f491f5ec7d72863"
metafile = true

[[files]]
file = "mods/enchanted-vertical-slabs.pw.toml"
hash = "144114b01c21d421a6043fff99eacc4dfc7f94d49491ec48d1cd327aef603b80"
metafile = true

[[files]]
file = "mods/enderman-overhaul.pw.toml"
hash = "8efa1757432143004e1958e70f01139ed350e85c9d5842346d30ec32231636de"
metafile = true

[[files]]
file = "mods/enhanced-celestials.pw.toml"
hash = "8bbe7d61a5e513ddb017e2269f624fae69b4596289fa7d32e7701ab1896603dd"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "b86acff1a5d3b2c11729d49de9923ab3a71f235d28c1e04d53ec5443609e233f"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "78e6623084bd14f68ef1335ae8a419238c4119188b90fd9e71faf45c4f049942"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "e6c08ca73289bc90f0d1930db05da8ccf6da68661f121c843fd6e3ff52875d10"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "6f5828b1dc08ba199fa350e06dddf8d9d8e1f2edd35501ca423d385a67a07fc7"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "a961245b2a04dede935966d6ef018174bfbe8def94a21cebe9877bb44ce59ba3"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/findme.pw.toml"
hash = "9c546c28d6a8094e65c522e7b6c7498905c3d1933c253481b09470f7b516a366"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "347c083e376de0992817d23c79ebf326ab297c35a27e95eb3b11bd28e89453c2"
metafile = true

[[files]]
file = "mods/friends-and-foes-forge.pw.toml"
hash = "841c078c18644b801b4f2d559e7246d1cb1df3726aec47de0a2ccf4e76b25188"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "97df06d07cba2990d9b252fb7ef701f5f57b3473fe5ade2b10f39829bb0e3f34"
metafile = true

[[files]]
file = "mods/geophilic.pw.toml"
hash = "643b6f675134f2b2dcf7601cf895a83dbb9ad56b1433e603ba36c8c1fc6c94bf"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "dbd756dd9bb17e6ecebcf2d7052a67a2da1c7dd378bc2089bc154916080fe031"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "140579adeaa079871292e4a38ec09aeb3346cf411808768051608782799ec11f"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "d73e856c660731a0a33a537299ce51a359d39a64daac6b4c5cdfa189c21a09fa"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "4c6d9e09a9cb4dbd1cae6a962da9a5838eab21a3cf8514784359d6ae0dc13199"
metafile = true

[[files]]
file = "mods/industrial-foregoing.pw.toml"
hash = "079b61922d3262615def99983bc9819e4de1e1cb0f797f410716d49bca087067"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "2235350d913f0e3ded91a238a5224d35a883c80dbdf1fd9d97fc363b20137ef9"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "c3c06a4839ecfd4717686f7394396a4fc66b7a2e8eabbdd51f23ab2a1099cc1e"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "298501d10980ed74135b92bb0ce3aea2008094c682176cdcf9e6274c03690407"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "0033c5a00c46d5d7b6cf77b19fa76ce5c78a613f3128dcadb3588fa5841ae489"
metafile = true

[[files]]
file = "mods/leashedplayer.pw.toml"
hash = "5a06073a04e7e009a9ac01ae1bf1033972d2672bb6b7c933fc16af9a6aff9b5f"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "5ce96ac040fca257f41959be41ad80ba790102dc91cccd8c09e81eed19fa6478"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0fb9b58c17adaf54255401dad1f6f7ff4d1971c42d0f1658dea4ca2171932089"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "47e2244b736fb660839538b160cc35e66f9f96e08e050c5e2cfd421dbe40eef7"
metafile = true

[[files]]
file = "mods/lobotomy-corporation-neoforge-mod.pw.toml"
hash = "8a8b69f0618818ac0476ccdfbfc4a04307382962a8f37b2e99df0e3c94f7732f"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "734da85a1770ed0489132d97ce86130c5dc1ae1800d5802d5ecb07f44e15468b"
metafile = true

[[files]]
file = "mods/monolib.pw.toml"
hash = "662a1d71f073d094dac04ea64e46d950b4f2975f69763a4844fad20d28167f26"
metafile = true

[[files]]
file = "mods/more-useful-copper.pw.toml"
hash = "62f2807b9c5887e6ac1adbdb9c818303c029ebefdff5ae2545ea9308e44dfa3c"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "1a06479cf811afadf8eb5b5a8cbb0c01bbda2f102530b44c86559b8450d3fb21"
metafile = true

[[files]]
file = "mods/no-realms-button.pw.toml"
hash = "f32de9c72847686fdb91cea47c7688eda0336b0f96ae11c234a30366d1ba5c42"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "d424a9260ef51bc102e56f0423d91dfabb739ccca8a86eb1c450ea631b739280"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "d43f3856a847580f75dca75ed9ac7948ca9bfabe7d0ac8d0b72fd186b01a629e"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
hash = "23f4322551960ed5fa21fae987c1a8c4ba5b154ad4cca697dae79b64749869ff"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "87fb28047d648087f2fe4891ddf9d3c394b9c5c29eaf4f3970fb7c32520e6fcf"
metafile = true

[[files]]
file = "mods/paxi.pw.toml"
hash = "74d96b4361faf4457a439bcc2a1656625a22dfc656164091e89a3ba676880867"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "225fad05428589bf0efe18c3540a9103eaf3280fa15ad1293ef04efa3318b14f"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "800fa24c4b8f7e5c3a54c00cacaa2c77b26ffccac66c51c8613168fca7a807dc"
metafile = true

[[files]]
file = "mods/powah.pw.toml"
hash = "3c5d410bf844b16dfd352793382fc16126fa1e9a5053a37c1c18de988b0f6394"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "951992721419dccf1f2e52d31846b9d663e94ed8ca6a5fd722e1d7e989c0198f"
metafile = true

[[files]]
file = "mods/pretty-rain.pw.toml"
hash = "59a575831eaaaf600d5f04891d2e8c34d268eb47c16526dc2c6ba951370becff"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "5c5c05a43cd40f175409ba8bb65bf09492b79a9d71e5dad95981b8e011d5182f"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "b954467adc6c354b2f56390a2d993f1c6815e5032ba264cd2b59c08685d4fb60"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "53b7873e229f9ffd722c84a3e277af26e10ed774d59f459c6e052db771c9620b"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "a0b5f9df48d1e4f7cff5954e6aeaac54b90121580db060720f00382a1483f73e"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "ce9ddada6ffd55a512149cc474c6a453281a997a5fdf1b7b4a2cc73f875e704a"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
hash = "73b1e4f6608fcd396acc3e4e7aa753d314c8810ef4caf831ed93d9932d93f896"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "734cbc49232e0c61d037fab4a379ac334634f847f2ab0fcb2e63e74df7a34cbd"
metafile = true

[[files]]
file = "mods/simpletms-tms-and-trs-for-cobblemon.pw.toml"
hash = "07bd73a0ddefeaa62c90762ed0bd67bb9da8265d742f82132bec330d042c8767"
metafile = true

[[files]]
file = "mods/small-ships.pw.toml"
hash = "5f0d17d236aad8f111b519c006988c8bf536ee569028c0a34690c4cc229b6403"
metafile = true

[[files]]
file = "mods/snow-under-trees.pw.toml"
hash = "833c98447ce84b8593d247e73a3b8d2064569875812ce891e0e47e0230a19e8f"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "997a436f81c6fddcfeabe64119bdaea00cebb3fe0525ef106a11ee85ee5c5d77"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a1fb713df668ed21dda0602e99cb23b991c8faff841e130d7aae46258c3d6a45"
metafile = true

[[files]]
file = "mods/sodium-extras.pw.toml"
hash = "c83dd1d3c2dde6081e6f89246fb3b89fa29734f5329f4cd6d949a5c0da55f35c"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "d193173f0f5dfb4a921d44e29e8d5cee656dd3a40872939069715bb482b66fc9"
metafile = true

[[files]]
file = "mods/sodium-options-mod-compat.pw.toml"
hash = "cef2df389d9ea783c940ff614e987223aa10b7653f8228d2f899071a151d60f6"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "347cac2ed12c9bc0561b6a59eeb4c121b10e5f3f71d54e9bf8d1343af57ef5b8"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "55dd892aa92eee1c15e2d6d7832fe36226548b181e8424130f320fb9668c0514"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "69288db622d6d7d89c732327c76aa697d4aa13137353dfd86bca9ff0406ce201"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "da7ee99189ad35aac094919fe33cac647d98533b23c228f10d4811f08989e2b8"
metafile = true

[[files]]
file = "mods/the-undergarden.pw.toml"
hash = "9b3b215e7962ed1095dc97a8612a8eb972cdf18a987891e4ca3ef673a9d023cd"
metafile = true

[[files]]
file = "mods/titanium.pw.toml"
hash = "ebdef9175f88e077b477bc7d06ce58450e5c00cf19e905ae373b0a8399f9dbef"
metafile = true

[[files]]
file = "mods/vics-point-blank.pw.toml"
hash = "04aeeeaefd75fb7af08852e44671385b4e135fdec8ddd2b58ae7459b96681276"
metafile = true

[[files]]
file = "mods/village-spawn-point.pw.toml"
hash = "911549e929c3a7d1d426d25fbbd5cc5d7941933dc88f59f89aae33b65fde1fe7"
metafile = true

[[files]]
file = "mods/visuality-forge.pw.toml"
hash = "47dd1e2ddbd36135ea4d6a9d1dd366fd6e8126ea3aaec1f98b662127cf90de9b"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "21f2fe5e9a7adc5ba8c5e8c47243002fe17b64dce90227d9ed8c3207af152422"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "97ad6c6905c54f487793a282b494586d3c10e04c4d5e15907133eaf8e88b0cd5"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "30e1fceff4fd5d769c044f2f8775656a641bf71993f3246d7965712bf2706afa"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "9de861902c7a3f7cc88f51a920bbf93be84f2beca2206073eb511a2963d37914"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "0df3146d35a0d29e2a7011aa4cd1c1233b1151edc13ff723af04e71458c8ea03"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "cb8dafb894f054f87041738ca31c7ce8e63a487568a008ac3a40bd6c05e74e32"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "4c2830674a08ec9f10af13e4d259aa60158bd306a3996d935e678281ec0cb5fd"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "dd107d6d7a3df330f3f37a60cc0bf258337d6f39406c01f455d86aee0080d7eb"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "ee63a5958eb1e0238257e2064d917bdaf8e528a47904bdfbe04a5758a1537e9f"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "0cc13a86488cf89d2989edc1636fa63c7efa2fe819246d42af35113458d5ba5b"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "19b478dba95d57f5e5c22958175e212368eae5c3eead77d2b258b64cceb0358c"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "9492d0854c51570bf2a6bace6267262e7573b94c40d721348996617e5d99480a"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "e223aea35b4bbe85f44e70be45c4fe9892d3729d27f61e5f6461c0a40612ed12"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "e2b23d0a1bf228d37ff8c3330150c24eb19cb875e113fae543191f34ded92ff8"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "9d9b074b2425fc4f19808b7d6df4a0baeae39a37e909107aaa85004df1a2d195"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "2541b092b92a82757e5d200a6093658e20db548bb8583abad3f4506ed04e5ce6"
metafile = true

[[files]]
file = "resourcepacks/better-lanterns.pw.toml"
hash = "17ea105b98d79a0be6ce20da3304f9ed1398c5d9d3ad24cea2c914a109ede78e"
metafile = true

[[files]]
file = "resourcepacks/better-leaves.pw.toml"
hash = "fcf82349376d262a92a072501f628782dab401720b1225cf8b3cc9e39ce56413"
metafile = true

[[files]]
file = "resourcepacks/cobblemon-classic-grass-pack.pw.toml"
hash = "754accb4ac44c21fa37c0216c6210b8e13e6c98248b3808d44be01c097c196c7"
metafile = true

[[files]]
file = "resourcepacks/cobblemon-interface.pw.toml"
hash = "5562e131499a2941c164919cd03e6c474ab9e418de32ea1548ee9aed663d15f4"
metafile = true

[[files]]
file = "resourcepacks/cobblesounds.pw.toml"
hash = "c84deb359b798cf27d533d35f801177695318421251372f53192acb68b398065"
metafile = true

[[files]]
file = "resourcepacks/vivillon-pride-patterns.pw.toml"
hash = "a1484d0e4c283ce0aabf0d0efabda9e8791c6ebb12286952b78ecf9671aa2b09"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "b90b25b61edd0dfe3bb3074e2343351c7a427d24bb1fa42c642a157b0fd887e4"
metafile = true
